platform:
  filename: "image_0.raw"
  disable_progress_bar: false
  leave_pbar_string: false
  render_3a: false
  # npy, png or both
  save_format: png

sensor_info:
  bayer_pattern: "grbg"
  #range: 65536
  hdr_bit_depth: 24
  bit_depth: 12
  width: 2880
  height: 1860
  output_bit_depth: 16
  sensor: "triton_490"
  endian_type: "ieee-be"
  data_format: "uint32"
  embedded_rows_top: 0
  embedded_rows_bottom: 0

# verified to match the SVS camera's companding curve
companding:
  is_enable: false
  is_debug: false
  pedestal: 0
  companded: True
  companded_pin: [1, 256, 512, 831, 994, 1319, 1984, 2530, 2871, 2968, 3258, 3541, 3855]
  companded_pout: [1, 256, 1024, 3900, 7800, 23400, 87315, 174630, 349260, 548241, 1736000, 5208000, 16777200]
  is_save: false

crop:
  is_enable: false
  is_debug: false
  crop_x_start: 1
  crop_y_start: 1
  new_width: 1920
  new_height: 1536
  is_save: false  

dead_pixel_correction: 
  is_enable: true
  dp_threshold: 64
  is_debug: false
  is_save: false

black_level_correction:
  is_enable: true
  r_offset: 16
  gr_offset: 16
  gb_offset: 16
  b_offset: 16
  is_linear: true
  r_sat: 4095
  gr_sat: 4095
  gb_sat: 4095
  b_sat: 4095
  is_save: false

oecf:
  is_enable: false
  is_save: false

digital_gain:
  is_debug: false
  is_auto: false
  is_enable: true
  # Array of pre-define Gains
  gain_array: [0.03125, 0.0625, 0.125, 0.25, 0.5, 1, 2, 4, 6, 8, 10, 12, 16, 32, 64]
  # Index of default gain - using lower gain for dark scene
  current_gain: 0  # Start with lowest gain
  ae_feedback: 0
  is_save: false

lens_shading_correction: 
  is_enable: false
  is_save: false

bayer_noise_reduction:
  is_enable: true
  filter_window: 7  # Increased for better noise reduction
  r_std_dev_s: 1.2  # Increased for dark scenes
  r_std_dev_r: 0.2  # Increased for dark scenes
  g_std_dev_s: 1.2
  g_std_dev_r: 0.2
  b_std_dev_s: 1.2
  b_std_dev_r: 0.2
  is_save: false

auto_white_balance:
  is_enable: false
  is_debug: false
  underexposed_percentage: 0.05
  overexposed_percentage: 0.05
  algorithm: "pca"
  percentage: 3.5

white_balance:
  is_enable: true
  is_debug: false
  is_auto: false
  # Manual gains for dark scene with red lights
  r_gain: 1.5  # Boost red channel
  b_gain: 0.8  # Reduce blue channel
  is_save: false

demosaic:
  is_save: false

color_correction_matrix:
  is_enable: true
  # Enhanced matrix for better color reproduction
  corrected_red: [1.8, -0.3, -0.2]    # Boost red
  corrected_green: [-0.2, 1.6, -0.1]   # Moderate green
  corrected_blue: [-0.1, -0.3, 1.4]    # Moderate blue
  is_save: false

gamma_correction:
  is_enable: true
  is_save: false

auto_exposure:
  is_enable: false
  is_debug: false
  center_illuminance: 2048  # Lower target for dark scene
  histogram_skewness: 0.9

# HDR tone mapping for dark scenes
hdr_durand:
  is_enable: true
  is_save: True
  is_debug: false
  sigma_space: 6.0
  sigma_color: 6.0
  contrast_factor: 1.2  # Reduced for dark scenes
  downsample_factor: 4

color_space_conversion: 
  conv_standard: 2
  is_save: false

color_saturation_enhancement:
  is_enable: true
  saturation_gain: 1.2  # Reduced for more natural colors

ldci:
  is_enable: true
  clip_limit: 1.5  # Reduced for dark scenes
  wind: 64
  is_save: false

sharpen:
  is_enable: false  # Disabled to reduce noise
  sharpen_sigma: 5
  sharpen_strength: 1

noise_reduction_2d:
  is_enable: true
  is_debug: false
  filter_window: 5
  sigma: 2.0  # Increased for dark scenes
  is_save: false

rgb_conversion:
  is_enable: true
  is_save: false

scale:
  is_enable: true
  is_debug: false
  scale_factor: 1
  is_save: false

yuv_conv_format:
  is_enable: true
  is_debug: false
  conv_type: 444
  is_save: false 
 
      #Imran Modifications 
tone_mapping:
  # The conversion wont run if csc is false
  is_enable: true
  tone_mapping_before_demosaic: yes
  tone_mapper: 'durand'
  #tone_mapper: 'reinhardPTRGlobal'
  #tone_mapper: 'TMOz'
  #tone_mapper: 'reinhdard_PTRLocal'
  is_save: false
  
TMOz_sorround_cond:
   XYZw1: [95.047, 100.0, 108.883]   # D65 white point for HDR image
   Lw1: 10000                         # HDR luminance
   Yb: 20                            # Background luminance
   XYZw2: [95.047, 100.0, 108.883]   # Display white point
   Lw2: 500                         # Output luminance
   surround: "avg"                   # Surround method
